# Generated by Django 2.0.2 on 2018-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(default='abc', max_length=20)),
                ('following', models.CharField(default='abc', max_length=20)),
            ],
        ),
    ]
