# Generated by Django 2.0.3 on 2018-04-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='following',
            field=models.ManyToManyField(related_name='_follows_following_+', to='login.Client'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Client'),
        ),
    ]
