# Generated by Django 2.0.2 on 2018-04-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='following',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='follows',
            name='person',
            field=models.CharField(max_length=20),
        ),
    ]
