# Generated by Django 2.0.2 on 2018-04-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ques_Ans', '0002_auto_20180408_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.IntegerField(default='0'),
        ),
    ]
