# Generated by Django 2.0.2 on 2018-04-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ques_Ans', '0003_auto_20180408_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
