# Generated by Django 2.0.2 on 2018-04-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ques_Ans', '0004_auto_20180408_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.IntegerField(default=0),
        ),
    ]
